### ISSUE TITLE
HTML panel support shorthand

### ISSUE THREAD

**Issue by monkindey** [egoist/codepan#10]
such as emmet ?

Any Thought?

**Comment by egoist** [comment]
I tried https://github.com/emmetio/codemirror but no luck, will retry it later

**Comment by egoist** [comment]
I still can't make emmet work for codemirror 😓

**Comment by ChenZerong** [comment]
I tried https://github.com/emmetio/codemirror/tree/webpack, this version can work. But how to use a unpublish version?

**Comment by egoist** [comment]
@ChenZerong guess `yarn add emmetio/codemirror#webpack` should work

**Comment by egoist** [comment]
Done and deployed! thanks to @ChenZerong
