### ISSUE TITLE
Requesting for help for an open source educational platform. 

### ISSUE THREAD

**Issue by adinarayaanraghu95** [egoist/codepan#34]
Hello there.
Tried finding your contact email ID , but unfortunately I couldn't find it anywhere and which is why I am sorry , I am writing here .

Kindly send a mail at adinarayanaraghu95@gmail.com

I could explain you further about the project so you could see if you could help us.

Alternativel you can also text at +91 8660626844 .

**Comment by egoist** [comment]
Sorry, the issue tracker is exclusively reserved for bug reports and feature requests.
