### ISSUE TITLE
Behind proxy with context

### ISSUE THREAD

**Issue by yuepywu** [egoist/codepan#44]
Hi there,

I found this pretty neat and cool 👍 , but when i try to run behind a proxy server with a context like "xxx.com/codepan/", the asset path is not going under the context, I am not familiar with vuejs with poi, is there anyway to achieve that?

Thanks!

(index):68 GET http://xxx.com/vendor.js net::ERR_ABORTED
(index):68 GET http://xxx.com/client.js net::ERR_ABORTED
(index):68 GET http://xxx.com/manifest.js net::ERR_ABORTED
(index):68 GET http://xxx.com/vendor.js net::ERR_ABORTED
(index):68 GET http://xxx.com/client.js net::ERR_ABORTED

**Comment by egoist** [comment]
Change this line https://github.com/egoist/codepan/blob/4f8b32e0f0bdcb6282d7c5713bcec2686ff8571a/poi.config.js#L25

to `/codepan/` or full url like `https://xx.com/codepan/`

**Comment by yuepywu** [comment]
@egoist 

Thanks for your quick reply!

i have tried the above configuration and "yarn dev" and the issue is still there, any thought? or you want some more information about my environment?

Thanks in advance!

**Comment by egoist** [comment]
seems I misunderstood you, if you are running `yarn dev` and proxy the dev server behind a proxy then the `homepage` option won't work since it only affect production environment which is produced by `yarn build`.

Instead you need to update `poi.config.js` like this:

```js
module.exports  = {
  // ...
  extendWebpack(config) {
    config.output.publicPath('https://...../codepan/')
  }
}
``

**Comment by yuepywu** [comment]
@egoist 

I have tried the above configurations with `homepage: '/'`, the assets are loaded successfully but another issue have came up.

When i access the page from `http://xxx.com/codepan/`,  it have appeared a designed 404 page with a "Return to Home Page" button. In this state the console have appeared the following:

```
[HMR] Waiting for update signal from WDS...
vue.runtime.esm.js:7407 Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
index.js:64 [WDS] Hot Module Replacement enabled.
widget.js:1 [Headway] Element provided by selector does not exist.
```

After that i have tried to click the Home Page button, the page have navigated to `http://xxx.com/` (context have been erased) and the interface have shown successfully and working properly such as preprocessing the pug and less to result panel.

During the troubleshooting, i have proxy the `/sockjs-node/` context with ws:// and `/sockjs-node/info` with http://.

Will you have any ideas to prevent the 404 page and preserving the context `http://xxx.com/codepan/`?

Thanks!

**Comment by yuepywu** [comment]
@egoist 

I have added `base` on router/index.js on vuejs level to assort the server-side proxy config, thanks!

```
const router = new Router({
  base: '/codepan',
  mode: 'history',
  routes: [
    {
      name: 'home',
      path: '/',
      component: EditorPage
    },
   ...
```
