### ISSUE TITLE
`get-imports` is missing

### ISSUE THREAD

**Issue by palaima** [egoist/codepan#49]
Hey

It seems that with your "last" commit 663c58b37f4228ebdd7c75769413f97f2250fcbb you have changed the way imports are parsed and I assume you forgot to add `get-imports.js` file or am I missing smth?

**Comment by egoist** [comment]
Ah yes I'll fix that later 😅

**Comment by egoist** [comment]
Fixed 😄 https://github.com/egoist/codepan/blob/master/src/utils/get-imports.js
